name: Laravel + Robot Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_mysql, mbstring

    - name: Install PHP dependencies
      run: | 
        cd /src/
        composer install

    - name: Generate key and run migrations
      run: |
        php artisan key:generate
        php artisan migrate --force
        php artisan db:seed # se necessário

    - name: Start Laravel server
      run: php artisan serve --host=0.0.0.0 --port=8000 &
      env:
        DB_HOST: 127.0.0.1

    - name: Wait for Laravel to boot
      run: sleep 10

    - name: Setup Python + Robot
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Robot Framework and Browser Library
      run: |
        pip install robotframework
        pip install robotframework-browser
        pip install robotframework-seleniumlibrary
        rfbrowser init

    - name: Run Robot Login Test
      run: robot tests/robot/login_test.robot
