name: Laravel + Robot Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      URL: http://127.0.0.1:8000

    steps:
    - uses: actions/checkout@v3

    - name: Instalar navegador e driver
      run: |
        sudo apt update
        sudo apt install -y wget unzip xvfb libnss3 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libxrandr2 libgtk-3-0 libasound2t64
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb || sudo apt -f install -y
        wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.92/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver  


    - name: Start X virtual framebuffer
      run: |
        sudo apt install -y xvfb
        nohup Xvfb :99 -screen 0 1920x1080x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_mysql, mbstring

    - name: Install PHP dependencies
      run: |
        cd src
        composer install

    - name: Generate key and run migrations
      run: |
        cd src
        php artisan key:generate
        php artisan migrate --force
        php artisan db:seed || true
      env:
        DB_HOST: 127.0.0.1

    - name: Start Laravel server
      run: |
        cd src
        nohup php artisan serve --host=127.0.0.1 --port=8000 > laravel.log 2>&1 &
      env:
        DB_HOST: 127.0.0.1


    - name: Wait for Laravel to boot
      run: sleep 10

    - name: Setup Python + Robot
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Robot Framework and SeleniumLibrary
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Run Robot Login Test
      run: robot tests/robot/login.robot
      env:
        DISPLAY: :99
